# pull official base image
FROM python:3.8-slim-buster

# set workdir
WORKDIR /home/producer

# update and install pipenv
RUN apt update --allow-releaseinfo-change && apt install -y pipenv && apt install -y htop && apt install -y vim 2>/dev/null

# copy project and install python packages
COPY Pipfile ./Pipfile
RUN pipenv install
COPY . .

COPY LinkToPy.py /root/.virtualenvs/producer-V67IOLBK/lib/python3.8/site-packages/LinkToPy/LinkToPy.py