FROM nginx:1.19.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.dev.conf /etc/nginx/conf.d

# TODO: Use bitnami image
# FROM bitnami/nginx:latest
# RUN rm /opt/bitnami/nginx/conf/nginx.conf
# COPY nginx.conf /opt/bitnami/nginx/conf
