# pull official base image
FROM python:3.14-slim-bookworm

# set workdir
WORKDIR /home/visualizer

# Install htop and vim for debugging
RUN apt update --allow-releaseinfo-change && apt install -y htop && apt install -y vim 2>/dev/null

# Install uv using the official binary
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy and install requirements directly to system packages in the container
COPY requirements.txt ./
RUN uv pip install --system -r requirements.txt

COPY . .